#!/bin/bash

# Copyright 2015 Sebastian Wezel <datgizmo@web.de>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3 dated June, 2007.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo 'Usage: sbc copy <text>'
    echo 'Copies text to the clipboard either wayland or X'
    exit
fi

if [[ -n $WAYLAND_DISPLAY ]]
then
    wl-copy $*
else
    xsel -i --clipboard $*
fi
