#!/bin/bash

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo 'Usage: sbc cp <source_file[ source_file_2[...]]> <destination>'
    echo 'Source files are the paths (absolute or relative) in SSH server machine'
    echo 'Destination is a valid path on SSH client machine'
    exit
fi

files_to_copy=${@:1:$((${#@} - 1))}
destination=${@:${#@}}
files_with_host=$(
    for file in $files_to_copy; do
        echo $REMOTE_USER@$REMOTE_HOST:$file
    done)

scp -P $REMOTE_PORT $files_with_host $destination
