#!/bin/bash

# Copyright 2012 Álvaro Justen
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3 dated June, 2007.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

function show_help() {
    echo 'Usage: sbc cp <source_file[ source_file_2[...]]> <destination>'
    echo 'Source files are the paths (absolute or relative) in SSH server machine'
    echo 'Destination is a valid path on SSH client machine'
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    show_help
    exit
fi

files_to_copy=${@:1:$((${#@} - 1))}
destination=${@:${#@}}

if [ -z "$destination" ] || [ -z "$files_to_copy" ]; then
    echo
    show_help
    exit
fi

files_with_host=$(
    for file in $files_to_copy; do
        [ "${file:0:1}" != "/" ] && file=$SBC_REMOTE_PWD/$file
        echo $SBC_REMOTE_USER@$SBC_REMOTE_HOST:$file
    done)

scp -P $SBC_REMOTE_PORT $files_with_host $destination
