#!/bin/bash

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo 'Usage: sbc gedit [file to edit]'
    echo 'Run gedit on SSH client machine editing a file in SSH server machine'
    exit
fi

filename=$1
if [ ${filename:0:1} = "/" ]; then
    filename=$filename
else
    filename=$REMOTE_PWD/$filename
fi

gedit ssh://$REMOTE_USER@$REMOTE_HOST:$REMOTE_PORT/$filename
