#!/bin/bash

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo 'Usage: sbc gvim [file to edit]'
    echo 'Run gvim on SSH client machine editing a file in SSH server machine'
    exit
fi

filename=$1
if [ ${filename:0:1} = "/" ]; then
    filename=$filename
else
    filename=$REMOTE_PWD/$filename
fi

gvim scp://$REMOTE_USER@$REMOTE_HOST:$REMOTE_PORT/$filename
