#!/bin/sh

# Copyright 2012 Álvaro Justen
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3 dated June, 2007.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo 'Usage: sbc notify <message to notify>'
    echo 'Send a notification in SSH client machine (generally appear near the clock)'
    exit
fi


notify-send "$*"
